language: python
sudo: false
python:
  - "2.7"
before_install:
  - openssl aes-256-cbc -K $encrypted_ddcefa9967f0_key -iv $encrypted_ddcefa9967f0_iv -in artsho_rsa.enc -out artsho_rsa -d
script:
  - make coverage
after_success:
  - chmod 600 artsho_rsa
  - ssh-add artsho_rsa
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make travis_deploy
