db:
  image: postgres
web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000 --settings=artsho.settings_compose
  volumes:
    - .:/var/www/artsho/artsho
  ports:
    - "8000:8000"
  links:
    - db
