# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20141205_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rkey',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='itempicture',
            name='rkey',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='newspicture',
            name='rkey',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
        migrations.AddField(
            model_name='picture',
            name='rkey',
            field=models.CharField(blank=True, default=b'', max_length=256),
        ),
    ]
