# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160511_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='extension',
            field=models.CharField(default=b'jpg', max_length=256),
        ),
        migrations.AddField(
            model_name='itempicture',
            name='extension',
            field=models.CharField(default=b'jpg', max_length=256),
        ),
        migrations.AddField(
            model_name='newspicture',
            name='extension',
            field=models.CharField(default=b'jpg', max_length=256),
        ),
        migrations.AddField(
            model_name='picture',
            name='extension',
            field=models.CharField(default=b'jpg', max_length=256),
        ),
    ]
