# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:32
from __future__ import unicode_literals

from django.db import migrations
import requests
import os.path
from django.conf import settings


def upload_pictures_to_reticulum(apps, schema_editor):
    Picture = apps.get_model("main", "Picture")
    for picture in Picture.objects.filter(rkey=""):
        fullpath = os.path.join(settings.MEDIA_ROOT, str(picture.image))
        extension = os.path.splitext(fullpath)[1].lower()
        basename = os.path.basename(fullpath)
        with open(fullpath, 'rb') as f:
            files = {
                'image': (basename, f),
            }
            r = requests.post(settings.RETICULUM_UPLOAD_BASE, files=files)
            picture.rkey = r.json()["hash"]
            picture.extension = extension
            picture.save()
            print("uploaded " + str(picture.image))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160511_2008'),
    ]

    operations = [
        migrations.RunPython(upload_pictures_to_reticulum),
    ]
