# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 20:49
from __future__ import unicode_literals

from django.db import migrations
import requests
import os.path
from django.conf import settings


def upload_pictures_to_reticulum(model):
    for picture in model.objects.filter(rkey=""):
        if str(picture.image) == "":
            continue
        fullpath = os.path.join(settings.MEDIA_ROOT, str(picture.image))
        extension = os.path.splitext(fullpath)[1].lower()
        basename = os.path.basename(fullpath)
        with open(fullpath, 'rb') as f:
            files = {
                'image': (basename, f),
            }
            r = requests.post(settings.RETICULUM_UPLOAD_BASE, files=files)
            picture.rkey = r.json()["hash"]
            picture.extension = extension
            picture.save()
            print("uploaded " + str(picture.image))


def upload_images(apps, schema_editor):
    upload_pictures_to_reticulum(apps.get_model("main", "Artist"))
    upload_pictures_to_reticulum(apps.get_model("main", "ItemPicture"))
    upload_pictures_to_reticulum(apps.get_model("main", "NewsPicture"))


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20160511_2032'),
    ]

    operations = [
        migrations.RunPython(upload_images),
    ]
