# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20160511_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='itempicture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspicture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='image',
        ),
        migrations.AlterField(
            model_name='artist',
            name='extension',
            field=models.CharField(default=b'.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='itempicture',
            name='extension',
            field=models.CharField(default=b'.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='newspicture',
            name='extension',
            field=models.CharField(default=b'.jpg', max_length=256),
        ),
        migrations.AlterField(
            model_name='picture',
            name='extension',
            field=models.CharField(default=b'.jpg', max_length=256),
        ),
    ]
